version: '3.8'

services:
  app:
    env_file:
      - diagram-gpt-ui/.env
    build:
      context: ./diagram-gpt-ui/
      dockerfile: ./Dockerfile.dev
    ports:
      - "127.0.0.1:3000:80"

  backend:
    build:
      context: ./diagram-gpt/
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8000:8000"